version: "3.9"

services:
  quest-tracker-db:
    image: postgres:17
    container_name: quest-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quest_tracker
      POSTGRES_USER: quest_admin
      POSTGRES_PASSWORD: "123456"
    volumes:
      - quest-tracker-db-data:/var/lib/postgresql/data
    networks:
      - quest-tracker-net
    restart: unless-stopped

volumes:
  quest-tracker-db-data:

networks:
  quest-tracker-net:
    driver: bridge
